import { FontAwesomeIcon, type FontAwesomeIconProps } from '@fortawesome/react-fontawesome'
import {
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faBagShopping,
  faBars,
  faBolt,
  faBoxOpen,
  faCheck,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faCircleInfo,
  faCircleXmark,
  faCopy,
  faGripLines,
  faMagnifyingGlass,
  faMinus,
  faPen,
  faPlus,
  faRotateRight,
  faSliders,
  faTriangleExclamation,
  faTrash,
  faXmark,
  faCommentDots,
  faChartLine,
  faTag,
  faGear,
  faLayerGroup,
  faListCheck,
  faLocationDot,
} from '@fortawesome/free-solid-svg-icons'

export const icons = {
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  logout: faArrowRightFromBracket,
  bag: faBagShopping,
  bars: faBars,
  bolt: faBolt,
  box: faBoxOpen,
  check: faCheck,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronRight: faChevronRight,
  info: faCircleInfo,
  xCircle: faCircleXmark,
  copy: faCopy,
  grip: faGripLines,
  search: faMagnifyingGlass,
  minus: faMinus,
  pen: faPen,
  plus: faPlus,
  rotate: faRotateRight,
  sliders: faSliders,
  warning: faTriangleExclamation,
  trash: faTrash,
  xmark: faXmark,
  whatsapp: faCommentDots,
  chart: faChartLine,
  tag: faTag,
  gear: faGear,
  layers: faLayerGroup,
  orders: faListCheck,
  location: faLocationDot,
} as const

export function Icon(props: FontAwesomeIconProps) {
  return <FontAwesomeIcon {...props} />
}
